version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
    -  MYSQL_ROOT_PASSWORD=password
    -  MYSQL_DATABASE=starwars
    -  MYSQL_USER=yoda
    -  MYSQL_PASSWORD=theforce
    volumes:
    - ./starwars-db.sql:/docker-entrypoint-initdb.d/starwars-db.sql:ro
    - ./data:/var/lib/mysql:rw